spring:
  mail:
    host: aaaa
    port: 587
    username: asfa
    password: fsafsa
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  profiles:
    active: loadInitialData
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
server:
  port: 8083
mail:
  from: q12434@wp.pl

